### ISSUE TITLE
(cloudlinux) lve-wrapper + duplicity-backup - backups are not saved

### ISSUE THREAD

**Issue by samapco** [zertrin/duplicity-backup#108]
Hello,

I'm not sure if this is an issue with cagefs or duplicity-backup.

I've been trying to wrap duplicity-backup with lve-wrapper so that I can limit the disk i/o during backup to prevent my server from hanging (i've experienced very high cpu usage upto 70) during backup.

This is how i run it
<code>
lve_suwrapper 10001 /root/duplicity-backup-master/duplicity-backup.sh -f
</code>

What happens is that, the files are compressed alright in the temp folder but they are not moved to the destination folder after the compression.

I'd really appreciate any help on this.

Thanks

**Comment by zertrin** [comment]
Hi @samapco,

Thanks for using duplicity-backup.sh!

I don't know anything about lve-wrapper (never heard of it), and I don't think this has anything to do with our wrapper script itself, or at least, that we could do anything to help.

You may have better luck by looking for help at the support channels related to lve-wrapper. Be sure to mention that you are using it on a bash wrapper script, which in turn call another program. (duplicity-backup.sh being only a wrapper around duplicity).

Since there is little chance that I could help more than this, I'm closing the issue, but feel free to continue commenting or reopen it if you think there's more that can be done in duplicity-backup.sh to help solving your problem.
