### ISSUE TITLE
Restore a directory with exclusion

### ISSUE THREAD

**Issue by guidtz** [zertrin/duplicity-backup#125]
Hello,

  I would want to restore a directory from the backup but I want to exclude on sub directory from this backup. How can I do that ?

For exemple 
restore /var/www/
but exclude /var/www/data

Thanks

**Comment by zertrin** [comment]
Hi,

Thanks for your question!

It's something that would be nice indeed, but that will not be taken care of by this wrapper script. Such a functionality should be implemented by duplicity first. Mybe you should ask for it upstream (see the duplicity mailing-lists https://lists.nongnu.org/mailman/listinfo/duplicity-talk or the duplicity bug-tracker https://launchpad.net/duplicity )

Since I think this should be implemented upstream, I will close this issue and mark it accordingly.

Feel free to continue commenting here or reopening this issue I you think there's something else that the wrapper script could do to help with this issue :wink:
