### ISSUE TITLE
[Feature Request] Support for pydrive and backblaze backends

### ISSUE THREAD

**Issue by uncertaintyiseverywhere** [zertrin/duplicity-backup#142]
Hi

Can we please have support for those? Google drive offers 15GB of free storage, backblaze offers 10GB. Plus, backblaze is currently by far the cheapest paid cloud storage option, at least among the providers I have researched.

Thanks,
t.

**Comment by zertrin** [comment]
Please see the readme, this script is just a wrapper around duplicity. If duplicity support them, then this script too ;)

**Comment by zertrin** [comment]
I'm closing, if you see something in the script that makes it incompatible with some backend that duplicity supports, feel free to reopen with details about the issue.

**Comment by uncertaintyiseverywhere** [comment]
Backblaze indeed works like a charm. Sorry for posting an issue before even trying.

I did try pydrive before posting however, and I couldn't get to work. For me to consider it 'supported', it should move up to the same level as aws, google cloud storage and swift, namely:
- it should work (might be my mistake though, I will keep on trying)
- get a note in the dependencies section of Readme.md, since it has its own dependency: pydrive
- get its own section in duplicity-backup.conf.example
- get its own variable GOOGLE_DRIVE_ACCOUNT_KEY or GOOGLE_DRIVE_SETTINGS

**Comment by uncertaintyiseverywhere** [comment]
OK, now I've managed to get google drive working as well. I followed [this guide](http://stackoverflow.com/a/34101322), and at the final step where you are given a link to verify the OAUTH process, I found that link in the log/ of duplicity-backup.sh. I pasted this link in the browser, got back the verification code, copied that and pasted it in the terminal window where duplicity-backup.sh was running (followed by hitting the enter key).

**Comment by zertrin** [comment]
Thanks for your feedback and happy to know it's working after a little bit of research :)

I understand your point, however since I've taken over the maintenance of this script in 2012, the number of supported backends by duplicity has greatly increased (compare [end of April 2012](https://web.archive.org/web/20120421020707/http://duplicity.nongnu.org/duplicity.1.html) with [April 2016](https://web.archive.org/web/20160402135323/http://duplicity.nongnu.org/duplicity.1.html) ;) ), and I can't follow up on each of them (not only can't I test them all myself, but I wouldn't have the time either), nor do I think that this script _needs_ to cover them all per default. The script should be flexible enough to allow using most of the backends only by modifying the config file (especially by using the correct `DEST` URL and taking advantage of the `STATIC_OPTIONS` variable)

Thus I'm only relying on patches submitted by people interested enough to take the time to add it properly to this script, test it, and to open a pull request here.

Since you've apparently made most of the work to make pydrive work with this script, maybe you could consider preparing a PR to add it, so that other people don't need to retrace your steps by themselves.
