### ISSUE TITLE
Correct place to put extra S3 params

### ISSUE THREAD

**Issue by n3b0r** [zertrin/duplicity-backup#193]
Hi,

I'm using duplicity 7.11 with Python 2.7. I'm trying to optimize the upload time using the feature `--s3-use-multiprocessing` that it's available since version Duplicity 7 according to his [documentation](http://duplicity.nongnu.org/vers7/duplicity.1.html).

I'm backing up large amount of data each night and I added the feature `--s3-use-multiprocessing` to `STATIC_OPTIONS` var, but the performance of tonight's backup was sightly worst than before. My question, is this the correct var to place this extra command?

Thanks

**Comment by zertrin** [comment]
Normally, yes that's the correct place. `STATIC_OPTIONS` allows you to pass custom arguments to duplicity directly.

As to whether the functionality you're using actually works as expected or not, I don't know. 

If you activate this script's debug mode (uncomment `ECHO` at the bottom of config file), you will get the actual command that this script generates to start duplicity. I suggest you review this, and test the resulting command directly.

In the end, this script is only a wrapper around duplicity. If some feature of duplicity fails to work, that's either because the command generated by this script doesn't match what is expected, or that's a duplicity issue altogether.

**Comment by n3b0r** [comment]
Thanks @zertrin I will do it and check the results. Also thanks for your awesome work with this script. I have been using it for a long time :)

**Comment by n3b0r** [comment]
The command seems to be correct. I will test the multithread and "asynchronous-upload" command together trying to improve the performance. 

Tomorrow, I will share the results just in case that can be useful for someone.

**Comment by n3b0r** [comment]
The combination between `--s3-use-multiprocessing` `--asynchronous-upload` is a time-killer. The backup time was reduced by 50%. Super recommended.

**Comment by zertrin** [comment]
Thanks for reporting back. I'll close this issue then 😉
