### ISSUE TITLE
Optional signing

### ISSUE THREAD

**Issue by vohof** [zertrin/duplicity-backup#76]
Hi, is it possible to make signing optional? Also, what are the benefits of signing. Thanks!

[Relavant line][don't cry for me argentina]

[don't cry for me argentina]: https://github.com/zertrin/duplicity-backup/blob/master/duplicity-backup.sh#L202

**Comment by zertrin** [comment]
While the encryption guarantees that no third party can read the backup files, the signature is used to guaranty that the backup file haven't been tampered by a third party.

Even though I'm not sure why you wouldn't want to sign the archive when using asymmetric encryption, I just did a quick search by curiosity to see if it was possible to asymmetrically encrypt (with a GPG-key) without signing with duplicity.

From what I have read this doesn't seem to be possible... If the `--sign-key` option is not given while the `--encrypt-key` option is, then the encryption key will be also used for signing...

However, it still seems possible to symmetrically encrypt the archive with a simple passphrase without signing.

**Comment by zertrin** [comment]
> Even though I'm not sure why you wouldn't want to sign the archive when using asymmetric encryption

After a second thought, you were maybe thinking to encrypt the backup with an encryption key, and hoping not to have to give any passphrase for doing so.

This is true if you only do full backups, however I never tried and thus don't know what are the exact parameters to give to duplicity for doing it successfully.

For incremental backups duplicity needs (sometimes) to decrypt some of the stored data (the manifests) in order to be able to know what to incrementally backup, and thus needs the passphrase.

See also this interesting discussion: https://lists.gnu.org/archive/html/duplicity-talk/2008-05/msg00059.html

**Comment by vohof** [comment]
I only wanted to avoid generating a gpg key for encryption. I tried modifying [this line][1] removing the `sign-key` part, and did seem to work. Here's my configuration:

```bash
ENCRYPTION=yes
HIDE_KEY_ID=no
PASSPHRASE='xxx'
GPG_ENC_KEY='290DAB13'
GPG_SIGN_KEY='290DAB13'
ROOT='/home/site1'
DEST='dpbx:///site1'
STATIC_OPTIONS='--full-if-older-than 14D'
CLEAN_UP_TYPE="remove-all-but-n-full"
CLEAN_UP_VARIABLE=2 #last two backups
LOGDIR="/var/log/duplicity-backup"
LOG_FILE="duplicity-`date +%Y-%m-%d_%H-%M`.log"
REMOVE_LOGS_OLDER_THAN=5 #days
export PATH="$PATH":/opt/duplicity/duplicity-0.7.0/bin
```

[1]: https://github.com/zertrin/duplicity-backup/blob/master/duplicity-backup.sh#L202

**Comment by zertrin** [comment]
Then, as written in the documentation on the example config file:

> .# Comment out if you're using only PASSPHRASE (symmetric encryption) or not using
> .# encryption at all.
> .#GPG_ENC_KEY=""
> .#GPG_SIGN_KEY=""

and you'll be using symmetric encryption with no need for a GPG key.
