### ISSUE TITLE
unable to backup 

### ISSUE THREAD

**Issue by Ericsante** [zertrin/duplicity-backup#86]
/usr/local/bin/duplicity-backup.sh -c /etc/duplicity-backup.conf -f
/usr/local/bin/duplicity-backup.sh: eval: line 490: unexpected EOF while looking for matching `''
/usr/local/bin/duplicity-backup.sh: eval: line 491: syntax error: unexpected end of file

**Comment by zertrin** [comment]
Please provide more information, otherwise I don't even know where to begin...

1. What is the result of `git log -1 --oneline`
2. Paste the content of your config file (without any password) at https://haste.zertrin.org/ and include the link here.

Thanks!

**Comment by Ericsante** [comment]
as requested

https://haste.zertrin.org/linacujoda.vala

[root@hephaestus duplicity-backup]# git log -l --online
commit 9e55b84837e7082c330de77838c82c3c6a6e5910
Merge: b34c7a5 258e68c
Author: zertrin <zertrin@gmail.com>
Date:   Fri Jan 23 20:00:47 2015 +0100

    Merge branch 'dev'

commit 258e68c95adcca22b41618268b6c4d0009427e53
Author: Philip <philip@yewtreeapps.com>
Date:   Fri Jan 23 17:02:25 2015 +0000

    copy whole array rather than one element

commit ea142128064f51c181d4b151d0b927267c36eb17
Author: Philip <philip@yewtreeapps.com>
Date:   Fri Jan 23 16:25:51 2015 +0000

    remove not on -z INCLIST check

commit 2e6e383538333b756a67f67059f6d27cbfbc4548
Author: zertrin <zertrin@gmail.com>
Date:   Wed Jan 21 16:29:42 2015 +0100

    Rework on the pull request to refactor the new code

commit b34c7a59867842a1faf44498e30cbaaaec42c540
Author: zertrin <zertrin@gmail.com>
Date:   Wed Jan 21 15:59:42 2015 +0100

    Include the include/exclude globbing file in the backup tarball if
present

-----------  SNIP --------------

**Comment by zertrin** [comment]
Hum I can't see yet where the problem could be... The lines around line 490 of the scripts are quite old and weren't changed recently.

Just an idea to be sure: if your passphrase contains a `$`, did you escape it as documented in the config file?

> Note: if you have a '$' in your passphrase, escape it with a '\'

**Comment by Ericsante** [comment]
there is no $ but I do have several forward slashes and a plus sign.  I
escaped them but it didn't make a difference.

E.

**Comment by zertrin** [comment]
There seems to be a trailing space in your config file here (after the backslash): `EXCLIST=( "/mnt/hd5/files/*/Trash" \ `

**Comment by Ericsante** [comment]
for simplicity I commented out the lines and still have the same error.

**Comment by Ericsante** [comment]
looking at the error a bit further I believe it has to do with the LOG_FILE
and the back ticks.

**Comment by zertrin** [comment]
Did you solve the problem and have you identified the root cause?

By lack of activity I'm closing this issue but feel free to reopen it if you still think there is a bug somewhere in the code that could be solved.

**Comment by nilp** [comment]
Hi zetrin, 
I know that is not the place to request but i need some help with this script and duplicity. I have problems with sftp and scp protocol. Can you provide me some contact method to you?

**Comment by zertrin** [comment]
Hi @nilp,

I'm sorry but I really can't provide private individual support on how to use duplicity-backup.sh, not because I don't want, but because I really don't have the time to. The number of problems that users can encounter are just too big (think at all the protocols supported by duplicity, and all the authentification and permissions problems of each of these protocols), and most of the time are not related to my wrapper script at all. 

As written in the *duplicity-backup.sh IS NOT duplicity* section in the readme, You need to install **and configure** duplicity **before** using duplicity-backup.sh.

Only if you can show that _you can make it work by using duplicity alone_, but not when using this wrapper, can I offer some help to find the cause of the problem (this would mean there is a problem with this script).

If you have problems with duplicity in general, then please use the support channels for duplicity first (see https://lists.nongnu.org/mailman/listinfo/duplicity-talk for example).

The best advice I can give is really to get it to work with duplicity alone before trying to use this script ;)

**Comment by nilp** [comment]
Ok I understand. I used with ftp and works properly.
