### ISSUE TITLE
how to force a full restoration in "/"

### ISSUE THREAD

**Issue by guidtz** [zertrin/duplicity-backup#87]
Hello,

  in case of a full backup for a virtual machine, how can I force a full restoration in / path ?

Thanks for your scripts they are very good for simply use duplicity.

Sincerely
Guidtz

**Comment by zertrin** [comment]
Hi,

sorry not to have reached out more quickly, I've been pretty busy IRL recently.

About your question, I'm not sure if I can give you the right answer. I never had to to that (because I don't backup `/` directly, only a handful of subpaths).

One of the ideas I can come with is:
  - Boot the system using another system which has duplicity and GPG available. 
  - Get the duplicity-backup .sh script on the temporary system
  - Import the duplicity-backup config file and (if necessary) the encrypting and signing key in the temporary system
  - Mount the `/` of the system to restore in the temporary system (let's assume it's at `/mnt/fooroot`)
  - Use duplicity-backup.sh to restore the complete archive to the destination `/mnt/foorot`
  - Fix the permissions if necessary :-/ (once again I'm not sure it's the easiest way to restore /)

If you are looking for a better (and probably more accurate) answer, just remember that duplicity-backup.sh is only a wrapper to duplicity, so if you get the answer on how to do it with duplicity (at places such as the duplicity forum or on stackoverflow/superuser), then you'll have the same answer for duplicity-backup.sh.

For now I'll close this issue (which isn't really one), feel free to comment here about your findings and/or reopen the issue if you think there is something that could be done/improved in duplicity-backup.sh to facilitate a full restoration.
