### ISSUE TITLE
Exclude don't work on master branch. 

### ISSUE THREAD

**Issue by dcmwai** [zertrin/duplicity-backup#98]
Hello there I've samba dir with recycle vfs which will move all deleted files to something 
/dir/folder_name/.recycled

How can I exclude all of the folder with ".recycled"

EXCLIST=(   "/dir/*/.recycled" \
        )

I try this and it was working before but it wasn't now.

Thank You.

**Comment by zertrin** [comment]
Hi, do you get any error message or anything that could help understand what is actually happening?

**Comment by dcmwai** [comment]
Hi Zertrin, 
How can I get more debug info on that?

I've try on "ECHO=$(which echo)" before for the mail issue but that don't help much.

Any other suggestion to enter debug mode?

**Comment by zertrin** [comment]
as a minimum could you paste 

* your config file (redacting any personal information)
* the resulting log file and/or the mail (redacting any personal information)

to https://zerobin.zertrin.org and give the link here.

Otherwise I just don't have enough info other than "it doesn't work" ;).

**Comment by zertrin** [comment]
Just to be sure, you are aware of the difference between `*` and `**` in the include/exclude filters of duplicity?

Excerpt from duplicity man page ( http://duplicity.nongnu.org/duplicity.1.html ) :

> The include, exclude, include-filelist, and exclude-filelist options accept some extended shell globbing patterns. These patterns can contain *, **, ?, and [...] (character ranges). As in a normal shell, * can be expanded to any string of characters not containing "/", ? expands to any character except "/", and [...] expands to a single character of those characters specified (ranges are acceptable). The new special pattern, **, expands to any string of characters whether or not it contains "/".

**Comment by dcmwai** [comment]
I'm sorry.
How should I configure
If I want to exclude ever folder(and subfolder) that start with ".recycled"
I'm trying both * and ** also can't seem to see the result
EXCLIST=(   "/dir/*/.recycled" )
EXCLIST=(   "/dir/**/.recycled" )

Please advise

Thank You

**Comment by zertrin** [comment]
Hi, this problem doesn't seem related to the wrapper script in itself, but to configure the include/exclude lists of duplicity. Moreover, you still didn't provide the additional information requested previously.

I'm sorry but I can't provide *private individual* support on how to use duplicity-backup.sh, not because I don't want, but because I really don't have the time to. The number of problems that users can encounter are just too big, and most of the time are not related to my wrapper script at all. 

As written in the *duplicity-backup.sh IS NOT duplicity* section in the readme, You need to install **and configure** duplicity **before** using duplicity-backup.sh.

Only if you can show that _you can make it work by using duplicity alone_, but _not_ when using this wrapper, can I offer some help to find the cause of the problem (this would mean there is a problem with this script).

If you have problems with duplicity in general, then please use the support channels for duplicity first (see https://lists.nongnu.org/mailman/listinfo/duplicity-talk for example).

The best advice I can give is really to get it to work with duplicity alone before trying to use this script ;)

**Comment by zertrin** [comment]
Closing for lack of feedback. Feel free to reopen if needed.
